# Generated by Django 5.2.6 on 2026-05-30 16:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackIngestRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason_code', models.CharField(db_index=True, max_length=64)),
                ('request_size', models.PositiveIntegerField(default=0)),
                ('platform_if_valid', models.CharField(blank=True, max_length=64)),
                ('game_version_if_valid', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('fixed', 'Fixed'), ('deferred', 'Deferred'), ('closed', 'Closed')], default='open', max_length=24)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_in_version', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssueRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('keywords_any', models.JSONField(blank=True, default=list)),
                ('keywords_all', models.JSONField(blank=True, default=list)),
                ('excluded_keywords', models.JSONField(blank=True, default=list)),
                ('applicable_versions', models.JSONField(blank=True, default=list)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='home.issue')),
            ],
            options={
                'ordering': ['issue', 'name'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='issues', to='home.tag'),
        ),
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(max_length=128, unique=True)),
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at_utc', models.DateTimeField()),
                ('feedback_schema_version', models.PositiveSmallIntegerField()),
                ('game_version', models.CharField(db_index=True, max_length=64)),
                ('build_channel', models.CharField(db_index=True, max_length=32)),
                ('platform', models.CharField(db_index=True, max_length=64)),
                ('locale', models.CharField(max_length=32)),
                ('feedback_policy_version', models.PositiveSmallIntegerField()),
                ('feedback_consent_timestamp_utc', models.DateTimeField()),
                ('message', models.TextField()),
                ('normalized_message', models.TextField()),
                ('save_snapshot', models.JSONField(blank=True, null=True)),
                ('save_schema_version', models.PositiveSmallIntegerField(default=0)),
                ('has_save_snapshot', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[('validated', 'Validated'), ('quarantined', 'Quarantined')], db_index=True, default='validated', max_length=16)),
                ('review_status', models.CharField(choices=[('untriaged', 'Untriaged'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned'), ('archived', 'Archived')], db_index=True, default='untriaged', max_length=16)),
                ('is_starred', models.BooleanField(db_index=True, default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('matched_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='home.issue')),
                ('tags', models.ManyToManyField(blank=True, related_name='reports', to='home.tag')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
