# Generated by Django 5.2.6 on 2026-05-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackIngressRateBucket',
            fields=[
                ('minute', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('request_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
